// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241022115243_AddIdentityTables")]
    partial class AddIdentityTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Entities.Application", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApplicationTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Applicat__3214EC072B1F9265");

                    b.HasIndex("ApplicationTypeId");

                    b.ToTable("Application", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ApplicationOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ApplicationOrderTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeliveryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PaymentId")
                        .HasColumnType("bigint");

                    b.Property<string>("PersonAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("ShippingCost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<long?>("ShoppingCartId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Applicat__3214EC07270C916F");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ApplicationOrderTypeId");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("ApplicationOrders");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ApplicationOrdersType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Applicat__3214EC0724535CF2");

                    b.ToTable("ApplicationOrdersTypes");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ApplicationType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Applicat__3214EC0773737997");

                    b.ToTable("ApplicationTypes");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("NameAr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name_Ar");

                    b.Property<string>("NameEn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name_En");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Brands__3214EC07FE6191F7");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.CitiesWhereDeliveiesWork", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeliveryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__CitiesWh__3214EC0714D1D3E2");

                    b.HasIndex("CityId");

                    b.HasIndex("DeliveryId");

                    b.ToTable("CitiesWhereDeliveiesWorks");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("NameAr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name_Ar");

                    b.Property<string>("NameEn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name_En");

                    b.HasKey("Id")
                        .HasName("PK__Cities__3214EC07A2F63C83");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Delivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Deliveri__3214EC07322C23DA");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<long?>("PaymentTypeId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Payments__3214EC07FFE12C42");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.PaymentsType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Payments__3214EC073B7ADCD8");

                    b.ToTable("PaymentsTypes");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.PeopleAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("CityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__PeopleAd__3214EC071308F9C3");

                    b.HasIndex("CityId");

                    b.HasIndex("PersonId");

                    b.ToTable("PeopleAddresses");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__People__3214EC0750368F63");

                    b.ToTable("People");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Phone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Phones__3214EC076BAE186A");

                    b.HasIndex("PersonId");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("NameAr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name_Ar");

                    b.Property<string>("NameEn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name_En");

                    b.Property<long?>("ProductCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Products__3214EC07813EF3B4");

                    b.HasIndex("BrandId");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ProductCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description_Ar");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description_En");

                    b.Property<string>("NameAr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name_Ar");

                    b.Property<string>("NameEn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name_En");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__ProductC__3214EC07FFD11FC9");

                    b.HasIndex(new[] { "NameEn" }, "UQ__ProductC__33341C8A8951CC7B")
                        .IsUnique()
                        .HasFilter("[Name_En] IS NOT NULL");

                    b.HasIndex(new[] { "NameAr" }, "UQ__ProductC__33347C132A72C059")
                        .IsUnique()
                        .HasFilter("[Name_Ar] IS NOT NULL");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ProductCategoryImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProductCategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__ProductC__3214EC073F10B0DE");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("ProductCategoryImages");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ProductImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__ProductI__3214EC07794FBA5A");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ProductReview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("NumberOfStars")
                        .HasColumnType("int");

                    b.Property<long?>("ReviewedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("SellerProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__ProductR__3214EC07ADEC10FB");

                    b.HasIndex("SellerProductId");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ProductsInShoppingCart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<long?>("SellerProductId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ShoppingCartId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Products__3214EC0709E6EA67");

                    b.HasIndex("SellerProductId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("ProductsInShoppingCarts");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__RefreshT__3214EC075E8158E9");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SellerProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("NumberInStock")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SellerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__SellerPr__3214EC07E45442F5");

                    b.HasIndex("ProductId");

                    b.ToTable("SellerProducts");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ShippingCost", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CityId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Shipping__3214EC075E9DA2D6");

                    b.HasIndex("CityId");

                    b.ToTable("ShippingCosts");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ShoppingCart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Shopping__3214EC07B8EE46F4");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("DataAccessLayer.Identity.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PersonId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Application", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.ApplicationType", "ApplicationType")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicationTypeId")
                        .HasConstraintName("FK_Application_ApplicationTypeId");

                    b.Navigation("ApplicationType");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ApplicationOrder", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Application", "Application")
                        .WithMany("ApplicationOrders")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("FK_ApplicationOrders_ApplicationId");

                    b.HasOne("DataAccessLayer.Entities.ApplicationOrdersType", "ApplicationOrderType")
                        .WithMany("ApplicationOrders")
                        .HasForeignKey("ApplicationOrderTypeId")
                        .HasConstraintName("FK_ApplicationOrders_ApplicationOrderTypeId");

                    b.HasOne("DataAccessLayer.Entities.Delivery", "Delivery")
                        .WithMany("ApplicationOrders")
                        .HasForeignKey("DeliveryId")
                        .HasConstraintName("FK_ApplicationOrders_DeliveryId");

                    b.HasOne("DataAccessLayer.Entities.Payment", "Payment")
                        .WithMany("ApplicationOrders")
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("FK_ApplicationOrders_PaymentId");

                    b.HasOne("DataAccessLayer.Entities.ShoppingCart", "ShoppingCart")
                        .WithMany("ApplicationOrders")
                        .HasForeignKey("ShoppingCartId")
                        .HasConstraintName("FK_ApplicationOrders_ShoppingCartId");

                    b.Navigation("Application");

                    b.Navigation("ApplicationOrderType");

                    b.Navigation("Delivery");

                    b.Navigation("Payment");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.CitiesWhereDeliveiesWork", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.City", "City")
                        .WithMany("CitiesWhereDeliveiesWorks")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_CitiesWhereDeliveiesWorks_CityId");

                    b.HasOne("DataAccessLayer.Entities.Delivery", "Delivery")
                        .WithMany("CitiesWhereDeliveiesWorks")
                        .HasForeignKey("DeliveryId")
                        .HasConstraintName("FK_CitiesWhereDeliveiesWorks_DeliveryId");

                    b.Navigation("City");

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Payment", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.PaymentsType", "PaymentType")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentTypeId")
                        .HasConstraintName("FK_Payments_PaymentTypeId");

                    b.Navigation("PaymentType");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.PeopleAddress", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.City", "City")
                        .WithMany("PeopleAddresses")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_PeopleAddresses_CityId");

                    b.HasOne("DataAccessLayer.Entities.Person", "Person")
                        .WithMany("PeopleAddresses")
                        .HasForeignKey("PersonId")
                        .HasConstraintName("FK_PeopleAddresses_PersonId");

                    b.Navigation("City");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Phone", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Person", "Person")
                        .WithMany("Phones")
                        .HasForeignKey("PersonId")
                        .HasConstraintName("FK_Phones_PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Product", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("FK_Products_BrandId");

                    b.HasOne("DataAccessLayer.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .HasConstraintName("FK_Products_ProductCategoryId");

                    b.Navigation("Brand");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ProductCategoryImage", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.ProductCategory", "ProductCategory")
                        .WithMany("ProductCategoryImages")
                        .HasForeignKey("ProductCategoryId")
                        .HasConstraintName("FK_ProductCategoryImages_ProductCategoryId");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ProductImage", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_ProductImages_ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ProductReview", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.SellerProduct", "SellerProduct")
                        .WithMany("ProductReviews")
                        .HasForeignKey("SellerProductId")
                        .HasConstraintName("FK_ProductReviews_SellerProductId");

                    b.Navigation("SellerProduct");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ProductsInShoppingCart", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.SellerProduct", "SellerProduct")
                        .WithMany("ProductsInShoppingCarts")
                        .HasForeignKey("SellerProductId")
                        .HasConstraintName("FK_ProductsInShoppingCarts_SellerProductId");

                    b.HasOne("DataAccessLayer.Entities.ShoppingCart", "ShoppingCart")
                        .WithMany("ProductsInShoppingCarts")
                        .HasForeignKey("ShoppingCartId")
                        .HasConstraintName("FK_ProductsInShoppingCarts_ShoppingCartId");

                    b.Navigation("SellerProduct");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SellerProduct", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Product", "Product")
                        .WithMany("SellerProducts")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_SellerProducts_ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ShippingCost", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.City", "City")
                        .WithMany("ShippingCosts")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_ShippingCosts_CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("DataAccessLayer.Identity.Entities.User", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Application", b =>
                {
                    b.Navigation("ApplicationOrders");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ApplicationOrdersType", b =>
                {
                    b.Navigation("ApplicationOrders");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ApplicationType", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.City", b =>
                {
                    b.Navigation("CitiesWhereDeliveiesWorks");

                    b.Navigation("PeopleAddresses");

                    b.Navigation("ShippingCosts");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Delivery", b =>
                {
                    b.Navigation("ApplicationOrders");

                    b.Navigation("CitiesWhereDeliveiesWorks");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Payment", b =>
                {
                    b.Navigation("ApplicationOrders");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.PaymentsType", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Person", b =>
                {
                    b.Navigation("PeopleAddresses");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("SellerProducts");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ProductCategory", b =>
                {
                    b.Navigation("ProductCategoryImages");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SellerProduct", b =>
                {
                    b.Navigation("ProductReviews");

                    b.Navigation("ProductsInShoppingCarts");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ShoppingCart", b =>
                {
                    b.Navigation("ApplicationOrders");

                    b.Navigation("ProductsInShoppingCarts");
                });
#pragma warning restore 612, 618
        }
    }
}
